Add .swift-format configuration and add a script to format

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -67,3 +67,18 @@ jobs:
       - run: swift build
         env:
           DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer/
+
+  format:
+    runs-on: ubuntu-latest
+    container:
+      image: swift:6.0.3
+    steps:
+      - uses: actions/checkout@v4
+      - run: ./Utilities/format.swift
+      - name: Check for formatting changes
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          git diff --exit-code || {
+            echo "::error::The formatting changed some files. Please run \`./Utilities/format.swift\` and commit the changes."
+            exit 1
+          }
